#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("ClickNDone.Droid.Resource", IsApplication=true)]

namespace ClickNDone.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Background = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Background_Party = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int barra_copyright = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int barra_copyright_44 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int btn_borrar = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int btn_cancelar_servicio = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int btn_cerrar = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int btn_cerrar_sesion = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int btn_cliente = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int btn_conectar = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int btn_consultar = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int btn_consultar_servicio = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int btn_enviar = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int btn_enviar_calificacion = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int btn_guardar = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int btn_menu = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int btn_menu_agenda = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int btn_menu_categorias = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int btn_menu_historial = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int btn_menu_historico = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int btn_menu_perfil = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int btn_menu_perfil_750 = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int btn_menu_promociones = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int btn_menu_ranking = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int btn_menu_sugerencias = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int btn_no_calificacion = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int btn_olvidapassword = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int btn_proveedor = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int btn_registrar = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int btn_registrate = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int btn_solicitar_telefono = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int btn_star = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int favorite = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int favorited = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int header_3_64 = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int ic_launcher = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int ic_tab_my_schedule_selected = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int ic_tab_my_schedule_unselected = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int ic_tab_sessions_selected = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int ic_tab_sessions_unselected = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int ic_tab_speakers_selected = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int ic_tab_speakers_unselected = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int ic_tab_whats_on_selected = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int ic_tab_whats_on_unselected = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int Icon = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int Icon2x = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int Icon_60 = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int icon_foodtruck = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int Icon_Small = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int Icon_Spotlight_40 = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int img_photo = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int logo_beauty = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int logo_home = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int logo_solutions = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int slideout = 2130837558;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050009
			public const int btnFinish = 2131034121;
			
			// aapt resource value: 0x7f050001
			public const int btnLogin = 2131034113;
			
			// aapt resource value: 0x7f050006
			public const int btnStart = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int btnStop = 2131034119;
			
			// aapt resource value: 0x7f05000a
			public const int button2 = 2131034122;
			
			// aapt resource value: 0x7f050008
			public const int lblStatus = 2131034120;
			
			// aapt resource value: 0x7f050004
			public const int myAddButton = 2131034116;
			
			// aapt resource value: 0x7f050002
			public const int myButton = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int myLabel = 2131034115;
			
			// aapt resource value: 0x7f050005
			public const int textMyCount = 2131034117;
			
			// aapt resource value: 0x7f05000b
			public const int textView1 = 2131034123;
			
			// aapt resource value: 0x7f050000
			public const int txtUsername = 2131034112;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Login = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int MainPage = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Second = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int UserSelection = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040002
			public const int ErrorTitle = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int Loading = 2130968579;
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
