// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace ClickNDone.iOS
{
	public partial class ProfileController : UIViewController
	{
		public ProfileController (IntPtr handle) : base (handle)
		{
		}
	}
}
