// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace ClickNDone.iOS
{
	public partial class SupplierServiceDetailController : UIViewController
	{
		public SupplierServiceDetailController (IntPtr handle) : base (handle)
		{
		}
	}
}
