// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;
using ClickNDone.Core;

namespace ClickNDone.iOS
{
	public partial class CancelServiceController : UIViewController
	{
		readonly OrdersModel ordersModel = (OrdersModel)DependencyInjectionWrapper.Instance.ServiceContainer ().GetService (typeof(OrdersModel));

		public CancelServiceController (IntPtr handle) : base (handle)
		{
		}

		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();

			txtClickCode.Text = ordersModel.RequestedOrder.ClickCode;
			txtState.Text = ordersModel.RequestedOrder.Status.ToString ();
			txtName.Text = ordersModel.RequestedOrder.Supplier.names;
			txtLastName.Text = ordersModel.RequestedOrder.Supplier.surnames;
			lblRanking.Text = "?";

			btnCancelConfirm.TouchUpInside += async(sender, e) =>
			{
				try {
					await ordersModel.ChangeOrderState(ServiceState.RECHAZADO_USUARIO);
					lblMsgText1.Text = "El servicio ha sido";
					lblMsgText2.Text = "cancelado con exito";
					btnCancelConfirm.Hidden = true;
					btnNotCancel.Hidden = true;
				}
				catch (Exception exc)
				{
					new UIAlertView("Oops!", exc.Message, null, "Ok").Show();
				}
			};

		}

		public override void ViewWillAppear(bool animated)
		{
			base.ViewWillAppear(false);
			ordersModel.IsBusyChanged += OnIsBusyChanged;
		}

		public override void ViewWillDisappear(bool animated)
		{
			base.ViewWillDisappear(false);
			ordersModel.IsBusyChanged -= OnIsBusyChanged;
		}

		void OnIsBusyChanged(object sender, EventArgs e)
		{
			btnCancelConfirm.Enabled = 
				btnNotCancel.Enabled =
					indicator.Hidden = !ordersModel.IsBusy;
		}

	}
}
