// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace DInteractive.iOS
{
	public partial class HistorialServiciosController : MyViewController
	{
		public HistorialServiciosController (IntPtr handle) : base (handle)
		{
		}

		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();
			this.LoadLeftbarButton ();
		}
	}
}
