// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;
using ClickNDone.Core;

namespace ClickNDone.iOS
{
	public partial class HomeLogoController : MyViewController
	{

		readonly UserModel loginViewModel = (UserModel)DependencyInjectionWrapper.Instance.ServiceContainer ().GetService (typeof(UserModel));


		public HomeLogoController (IntPtr handle) : base (handle)
		{
		}

		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();
			this.LoadLeftbarButton ();

			if(loginViewModel.UserType.Equals(UserType.CONSUMER))
				btnProveedorServico.Hidden = loginViewModel.UserType.Equals (UserType.SUPPLIER) ? false : true;
		}
	}
}
