// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;
using FlyoutNavigation;
using MonoTouch.Dialog;

namespace ClickNDone.iOS
{
	public partial class MainPageController : UIViewController
	{
		public static FlyoutNavigationController navigation;

		public MainPageController (IntPtr handle) : base (handle)
		{
		}

		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();
			System.Diagnostics.Debug.Write ("**HomeController - Device Token: " + AppDelegate._deviceToken);

			var LateralBar = new FlyoutNavigationController {//this will create a new instance of the FlyoutComponent
				NavigationRoot = new RootElement("Menu"){ //Here we create the root of the alements
					new Section("Seccion 1"){//with this code we create Sections
						new StyledStringElement ("Mi Perfil")    { BackgroundColor = UIColor.Clear, TextColor = UIColor.LightGray },
						new StyledStringElement ("Redimir Codigo")    { BackgroundColor = UIColor.Clear, TextColor = UIColor.LightGray },
					},
					new Section("Seccion 2"){
						new StyledStringElement ("Terminos y Condiciones")    { BackgroundColor = UIColor.Clear, TextColor = UIColor.LightGray },
					},
				},
				ViewControllers =  new [] {//here we link Controllers to the elements on the sections
					this.Storyboard.InstantiateViewController("TermsConditionsController") as UIViewController,//here we create the instances for the Controllers
					this.Storyboard.InstantiateViewController("TermsConditionsController") as UIViewController,
					this.Storyboard.InstantiateViewController("TermsConditionsController") as UIViewController,
				}
			};

			LateralBar.NavigationTableView.BackgroundView = new UIImageView (UIImage.FromBundle ("images/Background-Party.png"));
			LateralBar.NavigationTableView.SeparatorColor = UIColor.DarkGray;

			LateralBar.ToggleMenu();
			View.AddSubview (LateralBar.View);

		}

		public override void ViewDidDisappear (bool animated)
		{
			base.ViewDidDisappear (animated);
		}
	}
}
