// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;
using ClickNDone.Core;

namespace ClickNDone.iOS
{
	public partial class SupplierServiceController : UIViewController
	{
		readonly OrdersModel ordersModel = (OrdersModel)DependencyInjectionWrapper.Instance.ServiceContainer ().GetService (typeof(OrdersModel));
		readonly UserModel userModel = (UserModel)DependencyInjectionWrapper.Instance.ServiceContainer ().GetService (typeof(UserModel));

		public SupplierServiceController (IntPtr handle) : base (handle)
		{
		}

		public override async void ViewDidAppear (bool animated)
		{
			base.ViewDidAppear (animated);
			try {
				var requesterUser = await userModel.GetUserAsync (ordersModel.RequestedOrder.UserId, UserType.SUPPLIER);
				ordersModel.RequestedOrder.User = requesterUser;

				txtAddress.Text = ordersModel.RequestedOrder.Location;
				txtReference.Text = ordersModel.RequestedOrder.Reference;
				txtDate.Text = ordersModel.RequestedOrder.ReservationDate.ToString ();
				txtTime.Text = ordersModel.RequestedOrder.ReservationTime.ToString ();
				txtUserName.Text = ordersModel.RequestedOrder.User.names;
				txtUserLastName.Text = ordersModel.RequestedOrder.User.surnames;

			} catch (Exception exc) {
				new UIAlertView ("Oops!", exc.Message, null, "Ok").Show ();
			}
		}

		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();
			UITapGestureRecognizer labelAcceptTap = new UITapGestureRecognizer (() => {

			});
			lblAcceptService.UserInteractionEnabled = true;
			lblAcceptService.AddGestureRecognizer (labelAcceptTap);

			UITapGestureRecognizer labelRejectTap = new UITapGestureRecognizer (() => {

			});
			lblRejectService.UserInteractionEnabled = true;
			lblRejectService.AddGestureRecognizer (labelRejectTap);

		}

		public override void ViewWillAppear (bool animated)
		{
			base.ViewWillAppear (false);
			userModel.IsBusyChanged += OnIsBusyChanged;

		}

		public override void ViewWillDisappear (bool animated)
		{
			base.ViewWillDisappear (false);
			userModel.IsBusyChanged -= OnIsBusyChanged;
		}

		void OnIsBusyChanged (object sender, EventArgs e)
		{
			lblAcceptService.Enabled = 
				lblRejectService.Enabled = 
					indicator.Hidden = !userModel.IsBusy;
		}
	}
}
