// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;
using ClickNDone.Core;


namespace ClickNDone.iOS
{
	public partial class TermsConditionsController : UIViewController
	{

		readonly UserModel loginViewModel = (UserModel)DependencyInjectionWrapper.Instance.ServiceContainer ().GetService (typeof(UserModel));

		public TermsConditionsController ()
		{
			System.Diagnostics.Debug.Write ("Init this shit");
		}

		readonly TermsConditionsViewModel termsViewModel = (TermsConditionsViewModel)DependencyInjectionWrapper.Instance.ServiceContainer ().GetService (typeof(TermsConditionsViewModel));

		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();
			//TODO-Start using the service for terms and conditions.
			/*try 
			{
				//var terms = await termsViewModel.GetTermsConditions();
				//textTerms.Text = terms.terms;
				//textConditions.Text = terms.conditions;
			}
			catch (Exception exc)
			{
				new UIAlertView("Oops!", exc.Message, null, "Ok").Show();
			}*/
			if(loginViewModel.UserType.Equals(UserType.CONSUMER))
				textTerms.Text = "Consumer ** Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut " +
					"labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut " +
					"aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum " +
					"dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui " +
					"officia deserunt mollit anim id est laborum";
			else
				textTerms.Text = "Supplier ** Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut " +
					"labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut " +
					"aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum " +
					"dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui " +
					"officia deserunt mollit anim id est laborum";

		}

		public TermsConditionsController (IntPtr handle) : base (handle)
		{

		}

		public override void ViewWillAppear(bool animated)
		{
			base.ViewWillAppear(false);
			termsViewModel.IsBusyChanged += OnIsBusyChanged;
		}
		public override void ViewWillDisappear(bool animated)
		{
			base.ViewWillDisappear(false);
			termsViewModel.IsBusyChanged -= OnIsBusyChanged;
		}

		void OnIsBusyChanged(object sender, EventArgs e)
		{
			indicator.Hidden = !termsViewModel.IsBusy;
		}
	}
}
