// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;
using ClickNDone.Core;

namespace ClickNDone.iOS
{
	public partial class UserSelectionController : UIViewController
	{
		readonly UserModel loginViewModel = (UserModel)DependencyInjectionWrapper.Instance.ServiceContainer ().GetService (typeof(UserModel));

		public UserSelectionController (IntPtr handle) : base (handle)
		{
		}

		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();
			btnCustomer.TouchUpInside += (sender, e) => {
				loginViewModel.UserType = UserType.CONSUMER;
				PerformSegue ("OnUserSelection", this);
			};
			btnProvider.TouchUpInside += (sender, e) => {
				loginViewModel.UserType = UserType.SUPPLIER;
				PerformSegue ("OnUserSelection", this);
			};
		}

		public override bool PrefersStatusBarHidden ()
		{
			//return base.PrefersStatusBarHidden ();
			return false;
		}
	}
}
