// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;
using DInteractive.Core;

namespace DInteractive.iOS
{
	public partial class UserSelectionController : UIViewController
	{
		readonly CategoriesModel categoriesModel = (CategoriesModel)DependencyInjectionWrapper.Instance.ServiceContainer ().GetService (typeof(CategoriesModel));
		readonly UserModel userModel = (UserModel)DependencyInjectionWrapper.Instance.ServiceContainer ().GetService (typeof(UserModel));


		public UserSelectionController (IntPtr handle) : base (handle)
		{
		}

		public override void ViewDidAppear(bool animated)
		{
			base.ViewDidAppear (animated);
		}

		public override async void ViewDidLoad ()
		{
			try 
			{
				await categoriesModel.GetBusinessCategoriesAsync ();
			}
			catch(Exception exc) 
			{
				Console.WriteLine("Error on UserSelectionController - ViewDidLoad " + exc.Message);

			}

			btnCustomer.TouchUpInside += (sender, e) => 
			{
				userModel.UserType = UserType.CONSUMER;
				PerformSegue("OnUserSelected",this);
			};

			btnProvider.TouchUpInside += (sender, e) => 
			{
				userModel.UserType = UserType.SUPPLIER;
				PerformSegue("OnSupplierSelected",this);
			};


		}

		public override bool PrefersStatusBarHidden ()
		{
			//return base.PrefersStatusBarHidden ();
			return false;
		}
	}
}
